# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c7c67a8b575008491233e7940b1bf29b710c736013ba240c71f94a842ac8d7c174e25c95c352449273e2c73b2f5e0f23dd8e93d6fe7583ff45b6f8eb6905260
  edmunds_api_key: to_add
  edmunds_secret:  to_add

test:
  secret_key_base: cd6f7f0e809d7999c5fe0210d239cc12f702912ad6a95ed79afcc3f8c95373d72f93538e08bb548af9c434e26eeb00a6d674acb08916779141740ff957a9950c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
